// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dtaservice.proto

package dtaservice

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DocumentRequest) Validate() error {
	if this.ServiceName == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ServiceName", fmt.Errorf(`value '%v' must not be an empty string`, this.ServiceName))
	}
	return nil
}
func (this *TransformDocumentResponse) Validate() error {
	return nil
}
func (this *ListServiceRequest) Validate() error {
	return nil
}
func (this *OptionsRequest) Validate() error {
	return nil
}
func (this *ListServicesResponse) Validate() error {
	return nil
}
func (this *OptionsResponse) Validate() error {
	return nil
}
func (this *TransformPipeRequest) Validate() error {
	for _, item := range this.Pipe {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Pipe", err)
			}
		}
	}
	return nil
}
