// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dtaservice.proto

package dtaservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the document to be transformed
type DocumentRequest struct {
	FileName             string          `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Document             []byte          `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	ServiceName          string          `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Options              *_struct.Struct `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DocumentRequest) Reset()         { *m = DocumentRequest{} }
func (m *DocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentRequest) ProtoMessage()    {}
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{0}
}

func (m *DocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentRequest.Unmarshal(m, b)
}
func (m *DocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentRequest.Marshal(b, m, deterministic)
}
func (m *DocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentRequest.Merge(m, src)
}
func (m *DocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentRequest.Size(m)
}
func (m *DocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentRequest proto.InternalMessageInfo

func (m *DocumentRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *DocumentRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *DocumentRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *DocumentRequest) GetOptions() *_struct.Struct {
	if m != nil {
		return m.Options
	}
	return nil
}

// The response message containing the transformed message
type TransformDocumentResponse struct {
	Document             []byte   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Output               []string `protobuf:"bytes,2,rep,name=output,proto3" json:"output,omitempty"`
	Error                []string `protobuf:"bytes,3,rep,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformDocumentResponse) Reset()         { *m = TransformDocumentResponse{} }
func (m *TransformDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*TransformDocumentResponse) ProtoMessage()    {}
func (*TransformDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{1}
}

func (m *TransformDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformDocumentResponse.Unmarshal(m, b)
}
func (m *TransformDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformDocumentResponse.Marshal(b, m, deterministic)
}
func (m *TransformDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformDocumentResponse.Merge(m, src)
}
func (m *TransformDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_TransformDocumentResponse.Size(m)
}
func (m *TransformDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransformDocumentResponse proto.InternalMessageInfo

func (m *TransformDocumentResponse) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *TransformDocumentResponse) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TransformDocumentResponse) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListServiceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServiceRequest) Reset()         { *m = ListServiceRequest{} }
func (m *ListServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ListServiceRequest) ProtoMessage()    {}
func (*ListServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{2}
}

func (m *ListServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServiceRequest.Unmarshal(m, b)
}
func (m *ListServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServiceRequest.Marshal(b, m, deterministic)
}
func (m *ListServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServiceRequest.Merge(m, src)
}
func (m *ListServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ListServiceRequest.Size(m)
}
func (m *ListServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServiceRequest proto.InternalMessageInfo

type OptionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionsRequest) Reset()         { *m = OptionsRequest{} }
func (m *OptionsRequest) String() string { return proto.CompactTextString(m) }
func (*OptionsRequest) ProtoMessage()    {}
func (*OptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{3}
}

func (m *OptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionsRequest.Unmarshal(m, b)
}
func (m *OptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionsRequest.Marshal(b, m, deterministic)
}
func (m *OptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionsRequest.Merge(m, src)
}
func (m *OptionsRequest) XXX_Size() int {
	return xxx_messageInfo_OptionsRequest.Size(m)
}
func (m *OptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OptionsRequest proto.InternalMessageInfo

type ListServicesResponse struct {
	Services             []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesResponse) Reset()         { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()    {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{4}
}

func (m *ListServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesResponse.Unmarshal(m, b)
}
func (m *ListServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesResponse.Marshal(b, m, deterministic)
}
func (m *ListServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesResponse.Merge(m, src)
}
func (m *ListServicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesResponse.Size(m)
}
func (m *ListServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesResponse proto.InternalMessageInfo

func (m *ListServicesResponse) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type OptionsResponse struct {
	Services             string   `protobuf:"bytes,1,opt,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionsResponse) Reset()         { *m = OptionsResponse{} }
func (m *OptionsResponse) String() string { return proto.CompactTextString(m) }
func (*OptionsResponse) ProtoMessage()    {}
func (*OptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{5}
}

func (m *OptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionsResponse.Unmarshal(m, b)
}
func (m *OptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionsResponse.Marshal(b, m, deterministic)
}
func (m *OptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionsResponse.Merge(m, src)
}
func (m *OptionsResponse) XXX_Size() int {
	return xxx_messageInfo_OptionsResponse.Size(m)
}
func (m *OptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OptionsResponse proto.InternalMessageInfo

func (m *OptionsResponse) GetServices() string {
	if m != nil {
		return m.Services
	}
	return ""
}

type PipeService struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options              *_struct.Struct `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PipeService) Reset()         { *m = PipeService{} }
func (m *PipeService) String() string { return proto.CompactTextString(m) }
func (*PipeService) ProtoMessage()    {}
func (*PipeService) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{6}
}

func (m *PipeService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipeService.Unmarshal(m, b)
}
func (m *PipeService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipeService.Marshal(b, m, deterministic)
}
func (m *PipeService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipeService.Merge(m, src)
}
func (m *PipeService) XXX_Size() int {
	return xxx_messageInfo_PipeService.Size(m)
}
func (m *PipeService) XXX_DiscardUnknown() {
	xxx_messageInfo_PipeService.DiscardUnknown(m)
}

var xxx_messageInfo_PipeService proto.InternalMessageInfo

func (m *PipeService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PipeService) GetOptions() *_struct.Struct {
	if m != nil {
		return m.Options
	}
	return nil
}

type TransformPipeRequest struct {
	Document             []byte         `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	PipeService          []*PipeService `protobuf:"bytes,2,rep,name=pipeService,proto3" json:"pipeService,omitempty"`
	FileName             string         `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransformPipeRequest) Reset()         { *m = TransformPipeRequest{} }
func (m *TransformPipeRequest) String() string { return proto.CompactTextString(m) }
func (*TransformPipeRequest) ProtoMessage()    {}
func (*TransformPipeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{7}
}

func (m *TransformPipeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformPipeRequest.Unmarshal(m, b)
}
func (m *TransformPipeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformPipeRequest.Marshal(b, m, deterministic)
}
func (m *TransformPipeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformPipeRequest.Merge(m, src)
}
func (m *TransformPipeRequest) XXX_Size() int {
	return xxx_messageInfo_TransformPipeRequest.Size(m)
}
func (m *TransformPipeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformPipeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransformPipeRequest proto.InternalMessageInfo

func (m *TransformPipeRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *TransformPipeRequest) GetPipeService() []*PipeService {
	if m != nil {
		return m.PipeService
	}
	return nil
}

func (m *TransformPipeRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type TransformPipeResponse struct {
	Document             []byte   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Output               []string `protobuf:"bytes,2,rep,name=output,proto3" json:"output,omitempty"`
	Error                []string `protobuf:"bytes,3,rep,name=error,proto3" json:"error,omitempty"`
	LastTransformer      string   `protobuf:"bytes,4,opt,name=last_transformer,json=lastTransformer,proto3" json:"last_transformer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransformPipeResponse) Reset()         { *m = TransformPipeResponse{} }
func (m *TransformPipeResponse) String() string { return proto.CompactTextString(m) }
func (*TransformPipeResponse) ProtoMessage()    {}
func (*TransformPipeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a8961c93bb1a58, []int{8}
}

func (m *TransformPipeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransformPipeResponse.Unmarshal(m, b)
}
func (m *TransformPipeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransformPipeResponse.Marshal(b, m, deterministic)
}
func (m *TransformPipeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransformPipeResponse.Merge(m, src)
}
func (m *TransformPipeResponse) XXX_Size() int {
	return xxx_messageInfo_TransformPipeResponse.Size(m)
}
func (m *TransformPipeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransformPipeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransformPipeResponse proto.InternalMessageInfo

func (m *TransformPipeResponse) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *TransformPipeResponse) GetOutput() []string {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *TransformPipeResponse) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TransformPipeResponse) GetLastTransformer() string {
	if m != nil {
		return m.LastTransformer
	}
	return ""
}

func init() {
	proto.RegisterType((*DocumentRequest)(nil), "dtaservice.DocumentRequest")
	proto.RegisterType((*TransformDocumentResponse)(nil), "dtaservice.TransformDocumentResponse")
	proto.RegisterType((*ListServiceRequest)(nil), "dtaservice.ListServiceRequest")
	proto.RegisterType((*OptionsRequest)(nil), "dtaservice.OptionsRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "dtaservice.ListServicesResponse")
	proto.RegisterType((*OptionsResponse)(nil), "dtaservice.OptionsResponse")
	proto.RegisterType((*PipeService)(nil), "dtaservice.PipeService")
	proto.RegisterType((*TransformPipeRequest)(nil), "dtaservice.TransformPipeRequest")
	proto.RegisterType((*TransformPipeResponse)(nil), "dtaservice.TransformPipeResponse")
}

func init() { proto.RegisterFile("dtaservice.proto", fileDescriptor_19a8961c93bb1a58) }

var fileDescriptor_19a8961c93bb1a58 = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x96, 0xdb, 0xd1, 0xad, 0x6f, 0x0b, 0x2d, 0xa6, 0x1b, 0x21, 0x41, 0x90, 0x45, 0x02, 0x75,
	0x48, 0x6d, 0xb4, 0x22, 0x21, 0xc1, 0x0d, 0xb4, 0x23, 0x02, 0x94, 0xf5, 0xc0, 0xad, 0x4a, 0x5b,
	0xb7, 0x04, 0x92, 0x38, 0xd8, 0x4e, 0x27, 0x21, 0x4e, 0x1c, 0x11, 0x37, 0xfe, 0x04, 0xbf, 0x07,
	0x7e, 0x00, 0x12, 0xe2, 0x87, 0xa0, 0x38, 0x4e, 0xea, 0x74, 0xdd, 0xc4, 0x61, 0x37, 0xbf, 0x1f,
	0x7e, 0x9f, 0xe7, 0x79, 0xfd, 0x18, 0xba, 0x73, 0xe1, 0x73, 0xc2, 0x56, 0xc1, 0x8c, 0x0c, 0x13,
	0x46, 0x05, 0xc5, 0xb0, 0xce, 0x98, 0x77, 0x97, 0x94, 0x2e, 0x43, 0xe2, 0xfa, 0x49, 0xe0, 0xfa,
	0x71, 0x4c, 0x85, 0x2f, 0x02, 0x1a, 0xf3, 0xbc, 0xd3, 0x7c, 0xb2, 0x0c, 0xc4, 0xbb, 0x74, 0x3a,
	0x9c, 0xd1, 0xc8, 0x8d, 0xce, 0x02, 0xf1, 0x81, 0x9e, 0xb9, 0x4b, 0x3a, 0x90, 0xc5, 0xc1, 0xca,
	0x0f, 0x83, 0xb9, 0x2f, 0x28, 0xe3, 0x6e, 0x79, 0x54, 0xf7, 0x8a, 0xa9, 0x32, 0x9a, 0xa6, 0x0b,
	0x97, 0x0b, 0x96, 0xce, 0x44, 0x5e, 0x75, 0x7e, 0x20, 0xe8, 0x9c, 0xd0, 0x59, 0x1a, 0x91, 0x58,
	0x78, 0xe4, 0x63, 0x4a, 0xb8, 0xc0, 0x16, 0x34, 0x17, 0x41, 0x48, 0x26, 0xb1, 0x1f, 0x11, 0x03,
	0xd9, 0xa8, 0xdf, 0xf4, 0xf6, 0xb2, 0xc4, 0x2b, 0x3f, 0x22, 0xd8, 0x84, 0xbd, 0xb9, 0xea, 0x37,
	0x6a, 0x36, 0xea, 0xb7, 0xbd, 0x32, 0xc6, 0x47, 0xd0, 0x56, 0x5a, 0xf2, 0xbb, 0xf5, 0xec, 0xee,
	0x8b, 0xc6, 0x9f, 0xdf, 0xf7, 0x6b, 0x6f, 0x91, 0xd7, 0x52, 0x35, 0x39, 0xe6, 0x18, 0x76, 0x69,
	0x22, 0xe5, 0x19, 0x3b, 0x36, 0xea, 0xb7, 0x46, 0xb7, 0x87, 0x39, 0xcf, 0x61, 0xc1, 0x73, 0x78,
	0x2a, 0x79, 0x7a, 0x45, 0x9f, 0x43, 0xe0, 0xce, 0x98, 0xf9, 0x31, 0x5f, 0x50, 0x16, 0xad, 0x29,
	0xf3, 0x84, 0xc6, 0xbc, 0x4a, 0x0b, 0x6d, 0xd0, 0x3a, 0x80, 0x06, 0x4d, 0x45, 0x92, 0x66, 0x84,
	0xeb, 0xfd, 0xa6, 0xa7, 0x22, 0xdc, 0x83, 0x6b, 0x84, 0x31, 0xca, 0x8c, 0xba, 0x4c, 0xe7, 0x81,
	0xd3, 0x03, 0xfc, 0x32, 0xe0, 0xe2, 0x34, 0x27, 0xab, 0x76, 0xe2, 0x74, 0xe1, 0xc6, 0xeb, 0x9c,
	0x47, 0x91, 0x19, 0x41, 0x4f, 0xeb, 0xe3, 0x3a, 0x13, 0x25, 0x94, 0x1b, 0x48, 0x0e, 0x2e, 0x63,
	0x67, 0x00, 0x9d, 0x72, 0xca, 0xd6, 0x76, 0x54, 0x69, 0x1f, 0x43, 0xeb, 0x4d, 0x90, 0x10, 0x05,
	0x81, 0x31, 0xec, 0x68, 0x4f, 0x22, 0xcf, 0xfa, 0x1e, 0x6b, 0xff, 0xb9, 0xc7, 0xaf, 0x08, 0x7a,
	0xe5, 0x22, 0xb3, 0xf9, 0xc5, 0xbb, 0x5f, 0xb6, 0xc3, 0xa7, 0xd0, 0x4a, 0xd6, 0x54, 0xe4, 0x22,
	0x33, 0x2c, 0xcd, 0xcf, 0x1a, 0x53, 0x4f, 0xef, 0xad, 0xda, 0xa9, 0x5e, 0xb5, 0x93, 0xf3, 0x0d,
	0xc1, 0xfe, 0x06, 0x99, 0xab, 0x7e, 0x51, 0x7c, 0x04, 0xdd, 0xd0, 0xe7, 0x62, 0x22, 0x0a, 0x1c,
	0xc2, 0xa4, 0xe9, 0x9a, 0x5e, 0x27, 0xcb, 0x8f, 0xd7, 0xe9, 0xd1, 0xcf, 0x3a, 0x34, 0x4f, 0xc6,
	0xcf, 0x33, 0xea, 0x84, 0xe1, 0x4f, 0x70, 0xf3, 0x9c, 0xe3, 0xb0, 0xa5, 0x8b, 0xde, 0xf8, 0x3a,
	0xe6, 0x03, 0xbd, 0x78, 0xa1, 0x5b, 0x9d, 0xc3, 0x2f, 0xbf, 0xfe, 0x7e, 0xaf, 0x59, 0xce, 0x81,
	0xbb, 0x3a, 0x76, 0x0b, 0x55, 0x6e, 0xc9, 0xef, 0x19, 0x7a, 0x84, 0xdf, 0x43, 0x5b, 0xb7, 0x17,
	0xbe, 0xa7, 0x4f, 0x3e, 0x6f, 0x50, 0xd3, 0xbe, 0xa0, 0x5e, 0x3a, 0xcd, 0x31, 0x24, 0x28, 0xc6,
	0xdd, 0x0c, 0x54, 0x75, 0xba, 0x61, 0xc0, 0x05, 0xfe, 0x0c, 0xd7, 0x2b, 0x6f, 0x80, 0xed, 0xad,
	0x32, 0x34, 0xaf, 0x98, 0x87, 0x97, 0x74, 0x28, 0xbc, 0x87, 0x12, 0xcf, 0x76, 0xac, 0xed, 0x22,
	0x07, 0x99, 0x47, 0x32, 0xa5, 0x13, 0xd8, 0x55, 0x9f, 0x02, 0x9b, 0xfa, 0xd4, 0xea, 0x7f, 0x33,
	0xad, 0xad, 0x35, 0x85, 0x65, 0x49, 0xac, 0x7d, 0x7c, 0x4b, 0xd7, 0xa6, 0x0c, 0x3f, 0x6d, 0xc8,
	0xaf, 0xf0, 0xf8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x17, 0x06, 0xdf, 0x7e, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DTAServerClient is the client API for DTAServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DTAServerClient interface {
	// Request to transform a plain text document
	TransformDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*TransformDocumentResponse, error)
	ListServices(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	TransformPipe(ctx context.Context, in *TransformPipeRequest, opts ...grpc.CallOption) (*TransformPipeResponse, error)
	Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*OptionsResponse, error)
}

type dTAServerClient struct {
	cc *grpc.ClientConn
}

func NewDTAServerClient(cc *grpc.ClientConn) DTAServerClient {
	return &dTAServerClient{cc}
}

func (c *dTAServerClient) TransformDocument(ctx context.Context, in *DocumentRequest, opts ...grpc.CallOption) (*TransformDocumentResponse, error) {
	out := new(TransformDocumentResponse)
	err := c.cc.Invoke(ctx, "/dtaservice.DTAServer/TransformDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dTAServerClient) ListServices(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/dtaservice.DTAServer/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dTAServerClient) TransformPipe(ctx context.Context, in *TransformPipeRequest, opts ...grpc.CallOption) (*TransformPipeResponse, error) {
	out := new(TransformPipeResponse)
	err := c.cc.Invoke(ctx, "/dtaservice.DTAServer/TransformPipe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dTAServerClient) Options(ctx context.Context, in *OptionsRequest, opts ...grpc.CallOption) (*OptionsResponse, error) {
	out := new(OptionsResponse)
	err := c.cc.Invoke(ctx, "/dtaservice.DTAServer/Options", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DTAServerServer is the server API for DTAServer service.
type DTAServerServer interface {
	// Request to transform a plain text document
	TransformDocument(context.Context, *DocumentRequest) (*TransformDocumentResponse, error)
	ListServices(context.Context, *ListServiceRequest) (*ListServicesResponse, error)
	TransformPipe(context.Context, *TransformPipeRequest) (*TransformPipeResponse, error)
	Options(context.Context, *OptionsRequest) (*OptionsResponse, error)
}

// UnimplementedDTAServerServer can be embedded to have forward compatible implementations.
type UnimplementedDTAServerServer struct {
}

func (*UnimplementedDTAServerServer) TransformDocument(ctx context.Context, req *DocumentRequest) (*TransformDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransformDocument not implemented")
}
func (*UnimplementedDTAServerServer) ListServices(ctx context.Context, req *ListServiceRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (*UnimplementedDTAServerServer) TransformPipe(ctx context.Context, req *TransformPipeRequest) (*TransformPipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransformPipe not implemented")
}
func (*UnimplementedDTAServerServer) Options(ctx context.Context, req *OptionsRequest) (*OptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Options not implemented")
}

func RegisterDTAServerServer(s *grpc.Server, srv DTAServerServer) {
	s.RegisterService(&_DTAServer_serviceDesc, srv)
}

func _DTAServer_TransformDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTAServerServer).TransformDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtaservice.DTAServer/TransformDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTAServerServer).TransformDocument(ctx, req.(*DocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DTAServer_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTAServerServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtaservice.DTAServer/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTAServerServer).ListServices(ctx, req.(*ListServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DTAServer_TransformPipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransformPipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTAServerServer).TransformPipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtaservice.DTAServer/TransformPipe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTAServerServer).TransformPipe(ctx, req.(*TransformPipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DTAServer_Options_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DTAServerServer).Options(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dtaservice.DTAServer/Options",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DTAServerServer).Options(ctx, req.(*OptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DTAServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dtaservice.DTAServer",
	HandlerType: (*DTAServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransformDocument",
			Handler:    _DTAServer_TransformDocument_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _DTAServer_ListServices_Handler,
		},
		{
			MethodName: "TransformPipe",
			Handler:    _DTAServer_TransformPipe_Handler,
		},
		{
			MethodName: "Options",
			Handler:    _DTAServer_Options_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dtaservice.proto",
}
